'use client';

import { useState } from 'react';
import ContactForm from './contact-form';
import { ArrowUpRight, ArrowRight, Code2, Layers, Smartphone, Check, Menu, X, Globe2, Zap } from 'lucide-react';

const socials = [
  {name: 'Instagram', url: 'https://www.instagram.com/i_mmansoorkhan/'},
  {name: 'GitHub', url: 'https://github.com/muhammadmansoorkhan'},
  {name: 'LinkedIn', url: 'https://www.linkedin.com/in/itsmuhammadmansoorkhan'},
];
function SocialLinks(){return <nav className="social-links" aria-label="Social profiles">{socials.map(s=><a key={s.name} href={s.url} target="_blank" rel="noopener noreferrer">{s.name}<ArrowUpRight size={14}/></a>)}</nav>}

const services = [
  {icon: Globe2, name:'Business websites', text:'A professional home for your business. Clear content, responsive layouts, and a simple path from visitor to inquiry.'},
  {icon: Zap, name:'Landing pages', text:'One focused page for your next offer, campaign, or launch. Built around your message and a clear call to action.'},
  {icon: Code2, name:'Figma to front-end', text:'Turn your design into thoughtful React and Next.js code, with careful attention to spacing, typography, and every screen size.'},
  {icon: Smartphone, name:'Website fixes & updates', text:'Fix broken layouts, improve the mobile experience, or give an existing page the attention it needs.'},
];


export default function Home(){
 const [menu,setMenu]=useState(false);const [service,setService]=useState('Business website');
 return <main>
 <a className="skip-link" href="#main-content">Skip to content</a>
 <header className="site-header"><a href="#" className="wordmark">mansoor<span>.</span><small> / developer</small></a><nav className={menu?'navigation open':'navigation'} aria-label="Main navigation">{['Work','Services','About'].map(item=><a key={item} href={`#${item.toLowerCase()}`} onClick={()=>setMenu(false)}>{item}</a>)}<a className="nav-contact" href="#contact" onClick={()=>setMenu(false)}>Let's talk <ArrowUpRight size={16}/></a></nav><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
 <section id="main-content" className="hero section-wrap"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> AVAILABLE FOR FREELANCE PROJECTS</div><h1>Good ideas<br/>deserve <span className="blue">great<br/>websites.</span></h1><p>I'm Mansoor Khan, a front-end developer turning your ideas into clean, responsive websites that mean business.</p><div className="hero-actions"><a className="button primary" href="#contact">Let's build something <ArrowUpRight size={19}/></a><a className="text-link" href="#work">Explore my work <ArrowRight size={17}/></a></div><div className="hero-note"><span>BASED IN PAKISTAN</span><span className="note-line"/><span>WORKING WORLDWIDE</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-cross cross-one">+</div><div className="art-cross cross-two">+</div><div className="code-window"><div className="code-top"><div className="dots"><i/><i/><i/></div><span>portfolio.tsx</span><Code2 size={16}/></div><div className="code-body"><div><em>01</em><span className="purple">const</span> developer = {'{'}</div><div><em>02</em>&nbsp; name: <span className="green">'Mansoor Khan'</span>,</div><div><em>03</em>&nbsp; focus: <span className="green">'Front-end development'</span>,</div><div><em>04</em>&nbsp; stack: [</div><div><em>05</em>&nbsp; &nbsp; <span className="green">'React'</span>, <span className="green">'Next.js'</span>,</div><div><em>06</em>&nbsp; &nbsp; <span className="green">'Tailwind CSS'</span></div><div><em>07</em>&nbsp; ],</div><div><em>08</em>&nbsp; approach: <span className="green">'Details matter.'</span></div><div><em>09</em>{'}'};</div><div className="code-comment"><em>10</em>// Let's make your next idea real.</div></div><div className="code-bottom"><span><i/> READY TO BUILD</span><span>UTF-8 &nbsp; TSX</span></div></div><div className="floating-tag"><Layers size={20}/><div>Built with intention<small>From the first pixel to the last.</small></div></div><div className="art-caption">DESIGN → CODE → EXPERIENCE</div></div></section>
 <div className="stack-strip"><span>MY EVERYDAY TOOLKIT</span><div>{['React','Next.js','Tailwind CSS','JavaScript','HTML5','CSS3'].map(x=><b key={x}>{x}</b>)}</div></div>
 <section id="work" className="section-wrap content-section"><div className="section-heading"><div><div className="eyebrow muted">01 / SELECTED WORK</div><h2>Ideas, brought to life<span className="blue">.</span></h2></div><p>Real projects. Thoughtful interfaces.<br/>A little glimpse of what I build.</p></div><div className="projects-grid"><article className="project"><div className="project-meta"><span>BUSINESS WEBSITE · REAL ESTATE</span><h3><a href="https://www.stalwartrealtors.com" target="_blank" rel="noreferrer">Stalwart Realtors <ArrowUpRight size={23}/></a></h3><p>A responsive website presenting a property business, its projects, and ways for prospective buyers to get in touch.</p><a className="text-link" href="https://www.stalwartrealtors.com" target="_blank" rel="noopener noreferrer">Visit stalwartrealtors.com <ArrowUpRight size={16}/></a></div></article></div><div className="upcoming-projects"><div className="eyebrow muted">CURRENTLY IN DEVELOPMENT</div><div className="upcoming-grid">{['Legacy Developers', 'Brace & Beauty'].map(project=><article className="upcoming-card" key={project}><div className="progress-status"><span className="status-dot"/> IN PROGRESS</div><h3>{project}</h3><p>Website in development. Project images and details will be added when ready.</p><span className="upcoming-label">PREVIEW COMING SOON</span></article>)}</div></div></section>
 <section id="services" className="section-wrap content-section"><div className="section-heading"><div><div className="eyebrow muted">02 / HOW I CAN HELP</div><h2>Your next step,<br/>built right<span className="blue">.</span></h2></div><p>Launching something new or improving<br/>what you have? Let's make it work.</p></div><div className="services-grid">{services.map((s,i)=><article key={s.name} className="service-card"><div className="service-top"><s.icon size={24}/><span>0{i+1}</span></div><h3>{s.name}</h3><p>{s.text}</p><a href="#contact" onClick={()=>setService(i===0?'Business website':i===1?'Landing page':s.name)}>Discuss your project <ArrowUpRight size={16}/></a></article>)}</div></section>
 <section id="about" className="section-wrap about-section"><div><div className="eyebrow muted">03 / THE DEVELOPER BEHIND THE CODE</div><h2>A thoughtful approach.<br/>A hands-on developer<span className="blue">.</span></h2></div><div className="about-copy"><p className="about-lead">Hey, I'm Mansoor. I build for people who care about how their business shows up online.</p><p>I work with React, Next.js, and Tailwind CSS to create business websites, landing pages, and portfolios. My focus is simple: clear structure, careful implementation, and a smooth experience across devices.</p><div className="principles"><span><Check size={16}/> Clean, maintainable code</span><span><Check size={16}/> Mobile-first thinking</span><span><Check size={16}/> Clear communication</span><span><Check size={16}/> Attention to the details</span></div></div></section>
 <section id="contact" className="section-wrap contact-section"><div className="contact-copy"><div className="eyebrow"><span className="status-dot"/> LET'S MAKE IT HAPPEN</div><h2>Have an idea?<br/><span className="blue">Let's build it.</span></h2><p>Tell me what you're working on. Start with a short brief—your goals, the pages you need, and your ideal timeline.</p><div className="contact-note"><Globe2 size={18}/><span>Pakistan & worldwide · Remote collaboration</span></div><SocialLinks/></div><ContactForm service={service} onServiceChange={setService}/></section>
 <footer className="section-wrap"><a href="#" className="wordmark">mansoor<span>.</span></a><span>© {new Date().getFullYear()} Mansoor Khan</span><SocialLinks/><a className="text-link" href="#">Back to top <ArrowUpRight size={16}/></a></footer>
 </main>
}
